# CircleCI configuration for Android SDK
# See: https://circleci.com/docs/reference/configuration-reference
version: 2.1

jobs:
  lint:
    docker:
      - image: cimg/android:2026.02.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}-{{ checksum "attentive-android-sdk/build.gradle.kts" }}
            - gradle-
      - run:
          name: Run Android Lint
          command: ./gradlew lintDebug
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}-{{ checksum "attentive-android-sdk/build.gradle.kts" }}
      - store_artifacts:
          path: attentive-android-sdk/build/reports/lint-results-debug.html
          destination: lint-report.html

  test:
    docker:
      - image: cimg/android:2026.02.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}-{{ checksum "attentive-android-sdk/build.gradle.kts" }}
            - gradle-
      - run:
          name: Run Unit Tests
          command: ./gradlew testDebugUnitTest
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}-{{ checksum "attentive-android-sdk/build.gradle.kts" }}
      - store_test_results:
          path: attentive-android-sdk/build/test-results/testDebugUnitTest
      - store_artifacts:
          path: attentive-android-sdk/build/reports/tests/testDebugUnitTest
          destination: test-report

  build:
    docker:
      - image: cimg/android:2026.02.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}-{{ checksum "attentive-android-sdk/build.gradle.kts" }}
            - gradle-
      - run:
          name: Build SDK
          command: ./gradlew assembleRelease
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}-{{ checksum "attentive-android-sdk/build.gradle.kts" }}
      - store_artifacts:
          path: attentive-android-sdk/build/outputs/aar
          destination: aar

workflows:
  build-and-test:
    jobs:
      - lint
      - test
      - build:
          requires:
            - lint
            - test
